import type { Metadata } from 'next'
import { Geist, Geist_Mono, Unbounded } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/contexts/AuthContext'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const unbounded = Unbounded({
	subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={`${unbounded.className} antialiased`}>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	)
}
